services:
  - type: web
    name: puppeteer-login-test
    env: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'
      - key: NODE_ENV
        value: 'production'
    plan: free
